version: "3.1"

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test
    ports:
      - 5435:5432
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: test
    ports:
      - 27017:27017
    volumes:
      - ./no-sql/init.js:/docker-entrypoint-initdb.d/init.js:ro
